### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-T12-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-T12-3/main#317]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @chekjun for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T12-3/main/issues/251 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/238 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/204 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/172 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/160 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @eugenelim97 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T12-3/main/issues/251 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/204 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/176 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/175 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/174 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/173 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/172 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/171 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/160 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/156 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/151 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @liujiajun for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T12-3/main/issues/265 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/263 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/251 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/249 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/238 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/230 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/204 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/174 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @liushiru for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T12-3/main/issues/263 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/251 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/249 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/204 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/174 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/160 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/146 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/145 https://github.com/AY1920S1-CS2113T-T12-3/main/issues/144 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @RubaP

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-14 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
